// This file will be auto-generated by Supabase CLI
// For now, we'll define basic structure manually

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          created_by: string | null
          plan_type: 'free' | 'pro' | 'enterprise'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          created_by?: string | null
          plan_type?: 'free' | 'pro' | 'enterprise'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          created_by?: string | null
          plan_type?: 'free' | 'pro' | 'enterprise'
          created_at?: string
          updated_at?: string
        }
      }
      organization_members: {
        Row: {
          id: string
          user_id: string | null
          org_id: string | null
          role: 'owner' | 'admin' | 'member'
          invited_at: string
          joined_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          org_id?: string | null
          role?: 'owner' | 'admin' | 'member'
          invited_at?: string
          joined_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          org_id?: string | null
          role?: 'owner' | 'admin' | 'member'
          invited_at?: string
          joined_at?: string | null
          created_at?: string
        }
      }
      workspaces: {
        Row: {
          id: string
          name: string
          slug: string
          org_id: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          org_id?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          org_id?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      workspace_members: {
        Row: {
          id: string
          workspace_id: string | null
          member_id: string | null
          member_type: 'user' | 'agent'
          role: 'owner' | 'admin' | 'member'
          added_at: string
        }
        Insert: {
          id?: string
          workspace_id?: string | null
          member_id?: string | null
          member_type?: 'user' | 'agent'
          role?: 'owner' | 'admin' | 'member'
          added_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string | null
          member_id?: string | null
          member_type?: 'user' | 'agent'
          role?: 'owner' | 'admin' | 'member'
          added_at?: string
        }
      }
      issues: {
        Row: {
          id: string
          workspace_slug: string
          issue_number: number
          title: string
          description: string | null
          status: 'todo' | 'progress' | 'review' | 'done'
          priority: 'none' | 'low' | 'medium' | 'high' | 'urgent'
          assignee_ids: string[]
          workspace_id: string | null
          liveblocks_room_id: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_slug?: string
          issue_number?: number
          title?: string
          description?: string | null
          status?: 'todo' | 'progress' | 'review' | 'done'
          priority?: 'none' | 'low' | 'medium' | 'high' | 'urgent'
          assignee_ids?: string[]
          workspace_id?: string | null
          liveblocks_room_id?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_slug?: string
          issue_number?: number
          title?: string
          description?: string | null
          status?: 'todo' | 'progress' | 'review' | 'done'
          priority?: 'none' | 'low' | 'medium' | 'high' | 'urgent'
          assignee_ids?: string[]
          workspace_id?: string | null
          liveblocks_room_id?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      issue_labels: {
        Row: {
          id: string
          issue_id: string | null
          label: string
          color: string | null
          created_at: string
        }
        Insert: {
          id?: string
          issue_id?: string | null
          label: string
          color?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          issue_id?: string | null
          label?: string
          color?: string | null
          created_at?: string
        }
      }
      agents: {
        Row: {
          id: string
          name: string
          avatar_url: string | null
          workspace_id: string | null
          agent_brief_content: string | null
          capabilities: Record<string, any>
          integrations: string[]
          created_by: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          avatar_url?: string | null
          workspace_id?: string | null
          agent_brief_content?: string | null
          capabilities?: Record<string, any>
          integrations?: string[]
          created_by?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          avatar_url?: string | null
          workspace_id?: string | null
          agent_brief_content?: string | null
          capabilities?: Record<string, any>
          integrations?: string[]
          created_by?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      integrations: {
        Row: {
          id: string
          org_id: string | null
          provider: string
          credentials_encrypted: string | null
          settings: Record<string, any>
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id?: string | null
          provider: string
          credentials_encrypted?: string | null
          settings?: Record<string, any>
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string | null
          provider?: string
          credentials_encrypted?: string | null
          settings?: Record<string, any>
          created_at?: string
          updated_at?: string
        }
      }
      agent_conversations: {
        Row: {
          id: string
          agent_id: string | null
          user_id: string | null
          workspace_id: string | null
          message_content: string
          message_type: string
          created_at: string
        }
        Insert: {
          id?: string
          agent_id?: string | null
          user_id?: string | null
          workspace_id?: string | null
          message_content: string
          message_type: string
          created_at?: string
        }
        Update: {
          id?: string
          agent_id?: string | null
          user_id?: string | null
          workspace_id?: string | null
          message_content?: string
          message_type?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      plan_type: 'free' | 'pro' | 'enterprise'
      member_role: 'owner' | 'admin' | 'member'
      member_type: 'user' | 'agent'
      issue_status: 'todo' | 'progress' | 'review' | 'done'
      issue_priority: 'none' | 'low' | 'medium' | 'high' | 'urgent'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
} 